# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# activate powerlevel10k zsh customisations
# source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
source /opt/homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme

# compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename "${HOME}/.zshrc"

autoload -Uz compinit
compinit

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd
bindkey -v

# setup the git status in prompt
source "${HOME}/.git-flow-completion.zsh"

# enable ls colored output
autoload colors zsh/terminfo
colors
export CLICOLOR

# give me access to local utilities
PATH=${PATH}:/${HOME}/bin
export PATH

######## shell aliases #########
## formated json output ##
alias ppj="python -m json.tool"

## remove an ssh key from known hosts ##
alias rk='ssh-keygen -R'

## ls helpers ##
alias ll='ls -l'
alias la='ls -la'

## docker aliased commands ##
alias dcps='docker-compose ps'
alias dcud='docker-compose up -d'

## git aliased commands ##
alias gs='git status'
alias gc='git commit'

set-title(){
  print -Pn "\e]0;$@\a"
}

if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then source "${HOME}/.iterm2_shell_integration.zsh"; fi

if [ -f /usr/bin/kubectl ]; then source <(kubectl completion zsh); fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f "${HOME}/gcp/google-cloud-sdk/path.zsh.inc" ]; then source "${HOME}/gcp/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/gcp/google-cloud-sdk/completion.zsh.inc" ]; then source "${HOME}/gcp/google-cloud-sdk/completion.zsh.inc"; fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
